name: kiosk2
description: Issue.

version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  js: ^0.6.2
  dartz: ^0.9.1
  get_it: ^4.0.2
  dio: ^3.0.9
  equatable: ^1.2.0
  http_auth: ^0.2.9
  injectable: ^0.4.0+1
  auto_route: ^0.5.0
  flutter_bloc: ^6.0.0



dev_dependencies:
  build_runner: ^1.10.0
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.5.0

flutter:
  uses-material-design: true

  fonts:
    - family: Open Sans
      fonts:
        # https://fonts.google.com/specimen/Open+Sans
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
